### ISSUE TITLE
Issue with bootstrap theme

### ISSUE THREAD

**Issue by mpwaller** [wallerlab/reaktor#8]
when running ./grailsw prod run-war 

http://yserve2.uni-muenster.de:9090/reaktor/

![screen shot 2016-09-28 at 04 20 40](https://cloud.githubusercontent.com/assets/13583117/18898614/03028e80-8533-11e6-84cf-d910b4adde41.png)

**Comment by smcanana** [comment]
If you're using this code, it's because you didn't upload the bootstrap theme to git...didn't you have reservations about doing so? If you don't want to upload the theme, then you'll have to download it from the site yourself and add it to the code manually.

**Comment by mpwaller** [comment]
Thanks!

**Comment by mpwaller** [comment]
working now, closing this issue
