### ISSUE TITLE
Issue with clover plugin

### ISSUE THREAD

**Issue by mpwaller** [wallerlab/reaktor#9]
when we run in dev mode

./grailsw run-war 

we get an error:
![screen shot 2016-09-28 at 4 24 27 am](https://cloud.githubusercontent.com/assets/13583117/18898835/882a4c64-8534-11e6-8961-018c289f67c1.png)

**Comment by mpwaller** [comment]
removing the clover plugin and dependency in BuildConfig resolved the issue of running a war file in dev mode. 

I suggest we drop this dependency and move to another "free" solution.

@smcanana 
Agreed | Disagree   ?

**Comment by smcanana** [comment]
Sounds good to me.
